/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RoomController;
import Model.Phong;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author inusedname
 */
public final class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private DefaultTableModel modelRoom;

    public RoomController roomController;
    //public CustomerController customerController;
    //public InvoiceController invoiceController;

    public int currentChoose;

    public HomeFrm() {
        initComponents();
        this.setLocationRelativeTo(null);

        roomController = new RoomController();
        //customerController = new CustomerController();
        //invoiceController = new InvoiceController();

        modelRoom = (DefaultTableModel) roomsTable.getModel();
        //modelCustomer = (DefaultTableModel) customerTable.getModel();
        //modelInvoice = (DefaultTableModel) invoiceTable.getModel();

        refreshRoomTable();
        //refreshCustomerTable();
        //refreshInvoiceTable();
    }

    public void refreshRoomTable() {
        modelRoom.setRowCount(0);
        for (Phong t : roomController.getRoomList()) {
            modelRoom.addRow(new Object[]{
                t.getId(), t.getName(), t.getLoaiphong(), t.available});
        }
    }

    public void refreshCustomerTable() {

    }

    public void refreshInvoiceTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceTabName = new javax.swing.JTabbedPane();
        roomPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomsTable = new javax.swing.JTable();
        home_newRoomButton = new javax.swing.JButton();
        home_editRoomButton = new javax.swing.JButton();
        home_removeRoomButton = new javax.swing.JButton();
        customerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        invoicePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Loại Phòng", "Có sẵn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomsTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomsTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                roomsTableFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(roomsTable);

        home_newRoomButton.setText("Thêm Phòng");
        home_newRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_newRoomButtonActionPerformed(evt);
            }
        });

        home_editRoomButton.setText("Sửa Phòng");
        home_editRoomButton.setEnabled(false);
        home_editRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_editRoomButtonActionPerformed(evt);
            }
        });

        home_removeRoomButton.setText("Xoá Phòng");
        home_removeRoomButton.setEnabled(false);
        home_removeRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_removeRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomPanelLayout = new javax.swing.GroupLayout(roomPanel);
        roomPanel.setLayout(roomPanelLayout);
        roomPanelLayout.setHorizontalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(home_newRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(home_editRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(home_removeRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        roomPanelLayout.setVerticalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_newRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_editRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_removeRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        invoiceTabName.addTab("QL Phòng", roomPanel);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma KH", "Ten KH", "Dia chi", "So dien thoai", "Loai KH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        invoiceTabName.addTab("QL Khách Hàng", customerPanel);

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Phong", "Ten Khach", "Gio Checkin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invoiceTable);

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        invoiceTabName.addTab("QL Hoá Đơn", invoicePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceTabName)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceTabName)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_newRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_newRoomButtonActionPerformed
        // TODO add your handling code here:
        new AddPhong(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_home_newRoomButtonActionPerformed

    private void home_editRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_editRoomButtonActionPerformed
        // TODO add your handling code here:
        currentChoose = roomsTable.getSelectedRow();
        new EditPhong(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_home_editRoomButtonActionPerformed

    private void home_removeRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_removeRoomButtonActionPerformed
        // TODO add your handling code here:
        currentChoose = roomsTable.getSelectedRow();
        int result = JOptionPane.showConfirmDialog(this, "Xác nhận xoá", "Xoá", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            roomController.removeRoom(currentChoose);
        }
        refreshRoomTable();
    }//GEN-LAST:event_home_removeRoomButtonActionPerformed

    private void roomsTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomsTableFocusGained
        // TODO add your handling code here:
        home_editRoomButton.setEnabled(true);
        home_removeRoomButton.setEnabled(true);
    }//GEN-LAST:event_roomsTableFocusGained

    private void roomsTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomsTableFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_roomsTableFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton home_editRoomButton;
    private javax.swing.JButton home_newRoomButton;
    private javax.swing.JButton home_removeRoomButton;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JTabbedPane invoiceTabName;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JTable roomsTable;
    // End of variables declaration//GEN-END:variables

}
